version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - assistant
    networks:
      - fullstack

  backend:
    build: ./backend
    ports:
      - "4003:4003"
    depends_on:
      - assistant
    networks:
      - fullstack

  assistant:
    build: ./assistant
    ports:
      - "8000:8000"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
